package online.nwen.server.bo;

public enum ResponseCode {
    SUCCESS,
    SYSTEM_ERROR,
    REGISTER_USERNAME_EMPTY,
    REGISTER_USERNAME_FORMAT_ERROR,
    REGISTER_PASSWORD_EMPTY,
    REGISTER_PASSWORD_FORMAT_ERROR,
    REGISTER_NICKNAME_EMPTY,
    REGISTER_NICKNAME_FORMAT_ERROR,
    REGISTER_USERNAME_EXIST,
    REGISTER_NICKNAME_EXIST,
    AUTHENTICATE_USERNAME_IS_EMPTY,
    AUTHENTICATE_PASSWORD_IS_EMPTY,
    AUTHENTICATE_USERNAME_NOT_EXIST,
    AUTHENTICATE_PASSWORD_NOT_MATCH,
    SECURITY_TOKEN_IS_EMPTY,
    SECURITY_TOKEN_EXPIRED,
    SECURITY_TOKEN_PARSE_FAIL,
    SECURITY_CHECK_FAIL,
    ANTHOLOGY_TITLE_IS_EMPTY,
    ANTHOLOGY_TITLE_IS_TOO_LONG,
    ANTHOLOGY_SUMMARY_IS_TOO_LONG,
    USER_NOT_EXIST
}
